[server.http]

port = ":9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20

[server.http2]

port = ":9061"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.pem"
key = "cert/priv.key"

[server.http3]

port = ":9062"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.pem"
key = "cert/priv.key"