// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/internal/controller/uqs"
	"example/internal/server"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	messageController := uqs.NewMessageController()
	udpQuicServer := server.NewUDPQuicServer(messageController)
	toyBox := newApp(conf, udpQuicServer)
	return toyBox
}
