// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/internal/controller/uqs"
	"example/internal/server"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
	"github.com/inoth/toybox/udpsvr"
)

// Injectors from wire.go:

func initApp(dir string) *toybox.ToyBox {
	configMate := server.NewConfig(dir)
	messageController := uqs.NewMessageController()
	udpQuicServer := server.NewUDPQuicServer(messageController)
	toyBox := newApp(configMate, udpQuicServer)
	return toyBox
}

// wire.go:

func newApp(conf config.ConfigMate,

	udp *udpsvr.UDPQuicServer,
) *toybox.ToyBox {
	t := toybox.New(toybox.WithConfig(conf), toybox.WithServer(

		udp,
	),
	)
	return t
}
