[server.gin]

port = ":9059"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20

[server.gin2]

port = ":9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.pem"
key = "cert/priv.key"

[server.gin3]

port = ":9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.pem"
key = "cert/priv.key"


[server.proxy]

host = "http://localhost:9059"
