[server.gin]

port = ":9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20

[server.gin2]

port = ":9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.cer"
key = "cert/key.key"

[server.gin3]

port = "localhost:9060"
read_timeout = 10
write_timeout = 10
max_header_bytes = 20
cert = "cert/cert.cer"
key = "cert/key.key"