// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo-wire/internal/controller"
	"demo-wire/internal/provider"
	"demo-wire/internal/service"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	greeterService := service.NewGreeterService()
	greeterController := controller.NewGreeterController(greeterService)
	ginHttpServer := provider.NewHttpServer(greeterController)
	ginHttp2Server := provider.NewHttp2Server(greeterController)
	ginHttp3Server := provider.NewHttp3Server(greeterController)
	toyBox := newApp(conf, ginHttpServer, ginHttp2Server, ginHttp3Server)
	return toyBox
}
