// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo-wire/internal/biz"
	"demo-wire/internal/data/user"
	"demo-wire/internal/handler"
	"demo-wire/internal/provider"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/component/database/sqlite"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	sqliteComponent := database.NewGormDatabase(conf)
	userRepo := user.NewUserRepo(sqliteComponent)
	userUsecase := biz.NewUserUsecase(userRepo)
	userInfoHandler := handler.NewUserInfoHandler(userUsecase)
	prometheus := provider.NewMetric()
	ginHttpServer := provider.NewHttpServer(userInfoHandler, prometheus)
	profile := provider.NewProperty()
	toyBox := newApp(conf, ginHttpServer, prometheus, profile)
	return toyBox
}
