// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo-wire/internal/controller"
	"demo-wire/internal/controller/ws"
	"demo-wire/internal/provider"
	"demo-wire/internal/service"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	greeterService := service.NewGreeterService()
	messageController := ws.NewMessageController()
	websocketServer := provider.NewWebsocketServer(messageController)
	greeterController := controller.NewGreeterController(greeterService, websocketServer)
	prometheus := provider.NewMetric()
	ginHttpServer := provider.NewHttpServer(greeterController, prometheus)
	ginHttp2Server := provider.NewHttp2Server(greeterController)
	ginHttp3Server := provider.NewHttp3Server(greeterController)
	profile := provider.NewProperty()
	toyBox := newApp(conf, ginHttpServer, ginHttp2Server, ginHttp3Server, websocketServer, prometheus, profile)
	return toyBox
}
