[component.mysql]

host = "localhost"
port = 3306
user = "root"
passwd = "123456"
dbname = "mysql1"
max_idle_conns = 100
conn_max_idle_time = 300
max_open_conns = 100
conn_max_lifetime = 3600

[component.mysql2]

host = "localhost"
port = 3306
user = "root"
passwd = "123456"
dbname = "mysql2"
max_idle_conns = 100
conn_max_idle_time = 300
max_open_conns = 100
conn_max_lifetime = 3600


[component.logger]
debug = "log/debug/debug.log"
info = "log/info/info.log"
warn = "log/warn/warn.log"
err = "log/err/err.log"
max_size = 10
max_age = 15
max_backup = 30
compress = true
json = true