// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
	"mcp-quickstart/internal/handler"
	"mcp-quickstart/internal/provider"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	ipQueryHandler := handler.NewIPQueryHandler()
	mcpServer := provider.NewMCPServer(ipQueryHandler)
	toyBox := newApp(conf, mcpServer)
	return toyBox
}
