// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"demo-wssvr/internal/provider"
	"github.com/inoth/toybox"
	"github.com/inoth/toybox/config"
)

// Injectors from wire.go:

func initApp(conf config.ConfigMate) *toybox.ToyBox {
	websocketServer := provider.NewWebsocketServer()
	ginHttpServer := provider.NewHttpServer(websocketServer)
	toyBox := newApp(conf, ginHttpServer, websocketServer)
	return toyBox
}
